### PR TITLE
Debt

### PR DESCRIPTION
**Pull request by MrColdBeverage**
I have created the python file debt_graph.py to generate the graph for debt/gdp by year. I still have two main problems that I need to fix in the graph:

- [x] 1. The Y axis is not properly formatting into percentages, which is causing the info box from hovering to also not show percentages.

- [x] 2. The graph is a purple line, but I would like to fill it in to be solid like the original source.

@rickecon Please let me know what else you would like fixed or changed for this graph. I will be updating this to contain the deficit graph later today.

### CODE REVIEW

**Comment by MrColdBeverage** [comment]
I have finished both the debt and deficit graphs. I am beginning to update the deficit party plot.
@rickecon

**Comment by rickecon** [comment]
@MrColdBeverage:

Federal Debt plot:

- [ ] label every 10 years on x-axis (1900- 2050)
- [ ] vertical x-axis grid lines every 20 years (1900- 2040)
- [ ] label every 25 percent on y-axis (0 - 200%)
- [ ] horizontal y-axis grid lines every 50 % (0-200%)
- [ ] center text labels for "Great Depression" and "Great Recession".
- [ ] Change source text to "Congressional Budget Office, Richard W. Evans ...".
- [ ] Figure out why the hover tool shows two consecutive years' data when in between data points.

**Comment by rickecon** [comment]
@MrColdBeverage 

Deficit-interest plot:

- [ ] Change title of plot to include date range: "Total Deficits, Primary Deficits, and Net Interest: 2006-2051"
- [ ] Go back to original CBO colors that highlight the interest payments
- [ ] label every 5 years on x-axis (2006- 2050) with vertical grid lines every 5 years.
- [ ] Go 3 years of buffer space above max and below min on the y-axis (-18% to 3%)
- [ ] label every 3 percent on y-axis (-15% to 0%) with y-axis tick marks every 1% and horizontal grid lines associated with every 3% label
- [ ] Change source text to "Congressional Budget Office, Richard W. Evans ... Total Spending (Mar. 2021)."

**Comment by MrColdBeverage** [comment]
@rickecon I have made all of the corrections. I was not able to click on and check the above boxes for some reason, but I was able to fix everything except for the strange hovering problem where sometimes multiple years will display at once. I will keep looking into a way to fix that. Let me know if there are any other adjustments that need to be made.

**Comment by rickecon** [comment]
@MrColdBeverage . Really nice PR.

**Pull request merged**
